sudo: false
language: php
php: 
    - '5.6'

env:
  global:
    - setup=basic
    - coverage=no

before_install:
    - composer self-update

install:
    - composer create-project laravel/laravel
    - cd ./laravel
    - composer require jcorry/gootranslate:dev-master
    - composer update --require-dev

before_script:
    - cp .env.example .env
    - export APP_ENV=testing
    - export GOOGLE_API_KEY=XNj7t5upbFIqNSaS0de480YWckGb7136

script:
    - phpunit --filter ./vendor/jcorry/gootranslate/tests
    - ./vendor/bin/peridot ./vendor/jcorry/gootranslate/tests